name: education
description: "Book app project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.6
  lottie: ^3.1.2
  equatable: ^2.0.5
  get_it: ^8.0.0
  flutter_styled_toast: ^2.2.1
  pretty_dio_logger: ^1.4.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



flutter:


  uses-material-design: true


  assets:
    - assets/fonts/AlbertSans/
    - assets/fonts/
    - assets/animations/


  fonts:
    - family: AlbertSans
      fonts:
        - asset: assets/fonts/AlbertSans/AlbertSans-Black.ttf
          weight: 900
        - asset: assets/fonts/AlbertSans/AlbertSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlbertSans/AlbertSans-Light.ttf
          weight: 300
        - asset: assets/fonts/AlbertSans/AlbertSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/AlbertSans/AlbertSans-Regular.ttf
          weight: 400